### ISSUE TITLE
Travis errors when the vignette

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#71]
At the moment the [Travis CI tests are failing](https://travis-ci.org/ropensci/rentrez/builds/86243377). The error message suggests the vignette builder should be `rmarkdown` rather than `knitr`

```
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
Error: processing vignette 'rentrez_tutorial.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because rentrez_tutorial.Rmd appears to be an R Markdown v2 document.
```

 * [x] Update (some of?) the vignette, description and the travis script to use rmarkdown when rendering the vignette

**Comment by singmann** [comment]
Instead of changing the `VignetteBuilder`one can also simply change to the [container based infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure/) of Travis-CI by removing sudo. So instead of 
```
sudo: required
```
Use:
```
sudo: false
```
(in my case it also works without either statement.)

The problem with changing to `rmarkdown` as `VignetteBuilder` is that then `devtools::build_vignettes()` does not work anymore.

**Comment by singmann** [comment]
Hello there,
Actually, my previous response is wrong. It rather seems one needs to add `rmarkdown` to `Suggests` in the `DESCRIPTION` to get it to work with `VignetteBuilder: knitr`. Then it works with both the container based infrastructure and the "normal" one.
Sorry for the confusion.
